class Digital
{
	fonts[] =
	{
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital6",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital7",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital8",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital9",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital10",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital11",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital12",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital13",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital14",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital15",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital16",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital17",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital18",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital19",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital20",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital21",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital22",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital23",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital24",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital25",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital26",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital27",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital28",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital29",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital30",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital31",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital34",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital35",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital37",
		"\Edaly_Fonts\Fonts\DS-Digital\DS-Digital46"
	};
	spaceWidth=0.7;
	spacing=0.2;
};

class Papyrus
{
	fonts[] =
	{
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus6",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus7",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus8",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus9",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus10",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus11",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus12",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus13",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus14",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus15",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus16",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus17",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus18",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus19",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus20",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus21",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus22",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus23",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus24",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus25",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus26",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus27",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus28",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus29",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus30",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus31",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus34",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus35",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus37",
		"\Edaly_Fonts\Fonts\Papyrus\Papyrus46"
	};
	spaceWidth=0.7;
	spacing=0.2;
};
class SegoeScript
{
	fonts[] =
	{
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript6",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript7",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript8",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript9",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript10",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript11",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript12",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript13",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript14",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript15",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript16",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript17",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript18",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript19",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript20",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript21",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript22",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript23",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript24",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript25",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript26",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript27",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript28",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript29",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript30",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript31",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript34",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript35",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript37",
		"\Edaly_Fonts\Fonts\SegoeScript\SegoeScript46"
	};
	spaceWidth=0.7;
	spacing=0.2;
};

class Abuget
{
	fonts[] =
	{
		"\Edaly_Fonts\Fonts\Abuget\Abuget6",
		"\Edaly_Fonts\Fonts\Abuget\Abuget7",
		"\Edaly_Fonts\Fonts\Abuget\Abuget8",
		"\Edaly_Fonts\Fonts\Abuget\Abuget9",
		"\Edaly_Fonts\Fonts\Abuget\Abuget10",
		"\Edaly_Fonts\Fonts\Abuget\Abuget11",
		"\Edaly_Fonts\Fonts\Abuget\Abuget12",
		"\Edaly_Fonts\Fonts\Abuget\Abuget13",
		"\Edaly_Fonts\Fonts\Abuget\Abuget14",
		"\Edaly_Fonts\Fonts\Abuget\Abuget15",
		"\Edaly_Fonts\Fonts\Abuget\Abuget16",
		"\Edaly_Fonts\Fonts\Abuget\Abuget17",
		"\Edaly_Fonts\Fonts\Abuget\Abuget18",
		"\Edaly_Fonts\Fonts\Abuget\Abuget19",
		"\Edaly_Fonts\Fonts\Abuget\Abuget20",
		"\Edaly_Fonts\Fonts\Abuget\Abuget21",
		"\Edaly_Fonts\Fonts\Abuget\Abuget22",
		"\Edaly_Fonts\Fonts\Abuget\Abuget23",
		"\Edaly_Fonts\Fonts\Abuget\Abuget24",
		"\Edaly_Fonts\Fonts\Abuget\Abuget25",
		"\Edaly_Fonts\Fonts\Abuget\Abuget26",
		"\Edaly_Fonts\Fonts\Abuget\Abuget27",
		"\Edaly_Fonts\Fonts\Abuget\Abuget28",
		"\Edaly_Fonts\Fonts\Abuget\Abuget29",
		"\Edaly_Fonts\Fonts\Abuget\Abuget30",
		"\Edaly_Fonts\Fonts\Abuget\Abuget31",
		"\Edaly_Fonts\Fonts\Abuget\Abuget34",
		"\Edaly_Fonts\Fonts\Abuget\Abuget35",
		"\Edaly_Fonts\Fonts\Abuget\Abuget37",
		"\Edaly_Fonts\Fonts\Abuget\Abuget46"
	};
	spaceWidth=0.7;
	spacing=0.2;
};

class SeaweedScript
{
	fonts[] =
	{
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript6",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript7",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript8",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript9",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript10",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript11",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript12",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript13",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript14",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript15",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript16",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript17",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript18",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript19",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript20",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript21",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript22",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript23",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript24",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript25",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript26",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript27",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript28",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript29",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript30",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript31",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript34",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript35",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript37",
		"\Edaly_Fonts\Fonts\SeaweedScript\SeaweedScript46"
	};
	spaceWidth=0.7;
	spacing=0.2;
};

class Playball
{
	fonts[] =
	{
		"\Edaly_Fonts\Fonts\Playball\Playball6",
		"\Edaly_Fonts\Fonts\Playball\Playball7",
		"\Edaly_Fonts\Fonts\Playball\Playball8",
		"\Edaly_Fonts\Fonts\Playball\Playball9",
		"\Edaly_Fonts\Fonts\Playball\Playball10",
		"\Edaly_Fonts\Fonts\Playball\Playball11",
		"\Edaly_Fonts\Fonts\Playball\Playball12",
		"\Edaly_Fonts\Fonts\Playball\Playball13",
		"\Edaly_Fonts\Fonts\Playball\Playball14",
		"\Edaly_Fonts\Fonts\Playball\Playball15",
		"\Edaly_Fonts\Fonts\Playball\Playball16",
		"\Edaly_Fonts\Fonts\Playball\Playball17",
		"\Edaly_Fonts\Fonts\Playball\Playball18",
		"\Edaly_Fonts\Fonts\Playball\Playball19",
		"\Edaly_Fonts\Fonts\Playball\Playball20",
		"\Edaly_Fonts\Fonts\Playball\Playball21",
		"\Edaly_Fonts\Fonts\Playball\Playball22",
		"\Edaly_Fonts\Fonts\Playball\Playball23",
		"\Edaly_Fonts\Fonts\Playball\Playball24",
		"\Edaly_Fonts\Fonts\Playball\Playball25",
		"\Edaly_Fonts\Fonts\Playball\Playball26",
		"\Edaly_Fonts\Fonts\Playball\Playball27",
		"\Edaly_Fonts\Fonts\Playball\Playball28",
		"\Edaly_Fonts\Fonts\Playball\Playball29",
		"\Edaly_Fonts\Fonts\Playball\Playball30",
		"\Edaly_Fonts\Fonts\Playball\Playball31",
		"\Edaly_Fonts\Fonts\Playball\Playball34",
		"\Edaly_Fonts\Fonts\Playball\Playball35",
		"\Edaly_Fonts\Fonts\Playball\Playball37",
		"\Edaly_Fonts\Fonts\Playball\Playball46"
	};
	spaceWidth=0.7;
	spacing=0.2;
};

class BerlinSansFB
{
	fonts[] =
	{
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB6",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB7",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB8",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB9",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB10",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB11",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB12",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB13",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB14",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB15",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB16",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB17",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB18",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB19",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB20",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB21",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB22",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB23",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB24",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB25",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB26",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB27",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB28",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB29",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB30",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB31",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB34",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB35",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB37",
		"\Edaly_Fonts\Fonts\BerlinSansFB\BerlinSansFB46"
	};
	spaceWidth=0.7;
	spacing=0.2;
};
class AlexanderLettering
{
	fonts[] =
	{
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering6",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering7",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering8",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering9",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering10",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering11",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering12",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering13",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering14",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering15",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering16",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering17",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering18",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering19",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering20",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering21",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering22",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering23",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering24",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering25",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering26",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering27",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering28",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering29",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering30",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering31",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering34",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering35",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering37",
		"\Edaly_Fonts\Fonts\AlexanderLettering\AlexanderLettering46"
	};
	spaceWidth=0.7;
	spacing=0.2;
};
class Autography
{
	fonts[] =
	{
		"\Edaly_Fonts\Fonts\Autography\Autography6",
		"\Edaly_Fonts\Fonts\Autography\Autography7",
		"\Edaly_Fonts\Fonts\Autography\Autography8",
		"\Edaly_Fonts\Fonts\Autography\Autography9",
		"\Edaly_Fonts\Fonts\Autography\Autography10",
		"\Edaly_Fonts\Fonts\Autography\Autography11",
		"\Edaly_Fonts\Fonts\Autography\Autography12",
		"\Edaly_Fonts\Fonts\Autography\Autography13",
		"\Edaly_Fonts\Fonts\Autography\Autography14",
		"\Edaly_Fonts\Fonts\Autography\Autography15",
		"\Edaly_Fonts\Fonts\Autography\Autography16",
		"\Edaly_Fonts\Fonts\Autography\Autography17",
		"\Edaly_Fonts\Fonts\Autography\Autography18",
		"\Edaly_Fonts\Fonts\Autography\Autography19",
		"\Edaly_Fonts\Fonts\Autography\Autography20",
		"\Edaly_Fonts\Fonts\Autography\Autography21",
		"\Edaly_Fonts\Fonts\Autography\Autography22",
		"\Edaly_Fonts\Fonts\Autography\Autography23",
		"\Edaly_Fonts\Fonts\Autography\Autography24",
		"\Edaly_Fonts\Fonts\Autography\Autography25",
		"\Edaly_Fonts\Fonts\Autography\Autography26",
		"\Edaly_Fonts\Fonts\Autography\Autography27",
		"\Edaly_Fonts\Fonts\Autography\Autography28",
		"\Edaly_Fonts\Fonts\Autography\Autography29",
		"\Edaly_Fonts\Fonts\Autography\Autography30",
		"\Edaly_Fonts\Fonts\Autography\Autography31",
		"\Edaly_Fonts\Fonts\Autography\Autography34",
		"\Edaly_Fonts\Fonts\Autography\Autography35",
		"\Edaly_Fonts\Fonts\Autography\Autography37",
		"\Edaly_Fonts\Fonts\Autography\Autography46"
	};
	spaceWidth=0.7;
	spacing=0.2;
};
class Balista
{
	fonts[] =
	{
		"\Edaly_Fonts\Fonts\Balista\Balista6",
		"\Edaly_Fonts\Fonts\Balista\Balista7",
		"\Edaly_Fonts\Fonts\Balista\Balista8",
		"\Edaly_Fonts\Fonts\Balista\Balista9",
		"\Edaly_Fonts\Fonts\Balista\Balista10",
		"\Edaly_Fonts\Fonts\Balista\Balista11",
		"\Edaly_Fonts\Fonts\Balista\Balista12",
		"\Edaly_Fonts\Fonts\Balista\Balista13",
		"\Edaly_Fonts\Fonts\Balista\Balista14",
		"\Edaly_Fonts\Fonts\Balista\Balista15",
		"\Edaly_Fonts\Fonts\Balista\Balista16",
		"\Edaly_Fonts\Fonts\Balista\Balista17",
		"\Edaly_Fonts\Fonts\Balista\Balista18",
		"\Edaly_Fonts\Fonts\Balista\Balista19",
		"\Edaly_Fonts\Fonts\Balista\Balista20",
		"\Edaly_Fonts\Fonts\Balista\Balista21",
		"\Edaly_Fonts\Fonts\Balista\Balista22",
		"\Edaly_Fonts\Fonts\Balista\Balista23",
		"\Edaly_Fonts\Fonts\Balista\Balista24",
		"\Edaly_Fonts\Fonts\Balista\Balista25",
		"\Edaly_Fonts\Fonts\Balista\Balista26",
		"\Edaly_Fonts\Fonts\Balista\Balista27",
		"\Edaly_Fonts\Fonts\Balista\Balista28",
		"\Edaly_Fonts\Fonts\Balista\Balista29",
		"\Edaly_Fonts\Fonts\Balista\Balista30",
		"\Edaly_Fonts\Fonts\Balista\Balista31",
		"\Edaly_Fonts\Fonts\Balista\Balista34",
		"\Edaly_Fonts\Fonts\Balista\Balista35",
		"\Edaly_Fonts\Fonts\Balista\Balista37",
		"\Edaly_Fonts\Fonts\Balista\Balista46"
	};
	spaceWidth=0.7;
	spacing=0.2;
};
class Angelface
{
	fonts[] =
	{
		"\Edaly_Fonts\Fonts\Angelface\Angelface6",
		"\Edaly_Fonts\Fonts\Angelface\Angelface7",
		"\Edaly_Fonts\Fonts\Angelface\Angelface8",
		"\Edaly_Fonts\Fonts\Angelface\Angelface9",
		"\Edaly_Fonts\Fonts\Angelface\Angelface10",
		"\Edaly_Fonts\Fonts\Angelface\Angelface11",
		"\Edaly_Fonts\Fonts\Angelface\Angelface12",
		"\Edaly_Fonts\Fonts\Angelface\Angelface13",
		"\Edaly_Fonts\Fonts\Angelface\Angelface14",
		"\Edaly_Fonts\Fonts\Angelface\Angelface15",
		"\Edaly_Fonts\Fonts\Angelface\Angelface16",
		"\Edaly_Fonts\Fonts\Angelface\Angelface17",
		"\Edaly_Fonts\Fonts\Angelface\Angelface18",
		"\Edaly_Fonts\Fonts\Angelface\Angelface19",
		"\Edaly_Fonts\Fonts\Angelface\Angelface20",
		"\Edaly_Fonts\Fonts\Angelface\Angelface21",
		"\Edaly_Fonts\Fonts\Angelface\Angelface22",
		"\Edaly_Fonts\Fonts\Angelface\Angelface23",
		"\Edaly_Fonts\Fonts\Angelface\Angelface24",
		"\Edaly_Fonts\Fonts\Angelface\Angelface25",
		"\Edaly_Fonts\Fonts\Angelface\Angelface26",
		"\Edaly_Fonts\Fonts\Angelface\Angelface27",
		"\Edaly_Fonts\Fonts\Angelface\Angelface28",
		"\Edaly_Fonts\Fonts\Angelface\Angelface29",
		"\Edaly_Fonts\Fonts\Angelface\Angelface30",
		"\Edaly_Fonts\Fonts\Angelface\Angelface31",
		"\Edaly_Fonts\Fonts\Angelface\Angelface34",
		"\Edaly_Fonts\Fonts\Angelface\Angelface35",
		"\Edaly_Fonts\Fonts\Angelface\Angelface37",
		"\Edaly_Fonts\Fonts\Angelface\Angelface46"
	};
	spaceWidth=0.7;
	spacing=0.2;
};
